[package]
name = "lsmtree"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
tracing = { version = "0.1", default-features = false, features = ["log", "std"] }

[dev-dependencies]
pretty_env_logger = "0.5"
tempdir = "0.3"
